// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDbGCMs34-0TnbrVdjIMLUiHah_aNLTo',
    appId: '1:1077717598939:web:b5eaf839621c27588502fe',
    messagingSenderId: '1077717598939',
    projectId: 'new-pharmacy-stilo',
    authDomain: 'new-pharmacy-stilo.firebaseapp.com',
    storageBucket: 'new-pharmacy-stilo.appspot.com',
    measurementId: 'G-HL22JKZPES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2fsedaJ4WCXY8aN5ERPprF8i1p7kp91Q',
    appId: '1:1077717598939:android:4b808ff9efd4a0368502fe',
    messagingSenderId: '1077717598939',
    projectId: 'new-pharmacy-stilo',
    storageBucket: 'new-pharmacy-stilo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsSP9QUUDZYpgVDuoasmAwL5SRcZYZ1cQ',
    appId: '1:1077717598939:ios:f5a8b881709e3ee18502fe',
    messagingSenderId: '1077717598939',
    projectId: 'new-pharmacy-stilo',
    storageBucket: 'new-pharmacy-stilo.appspot.com',
    iosBundleId: 'com.smtmartamtech.FarmacieStilo',
  );
}
